# Generated by Django 3.1.6 on 2021-04-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigator',
            name='url',
            field=models.URLField(default=1, help_text='Enter field link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='navigator',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='navigator',
            name='website',
            field=models.CharField(help_text='Enter alternative name', max_length=30),
        ),
    ]
