# Generated by Django 3.1.6 on 2021-04-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210402_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigator',
            name='website',
            field=models.CharField(help_text='Enter alternative name', max_length=255),
        ),
    ]
