# Generated by Django 3.1.6 on 2021-04-02 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210402_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigator',
            name='description',
        ),
    ]
